version: '3.8'

services:
  backend: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - '3000:3000'

  database:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
